<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Question;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $questions = [
            [
                'question' => 'Qual é o nome do encanador protagonista da série Super Mario?',
                'option_a' => 'Luigi',
                'option_b' => 'Mario',
                'option_c' => 'Wario',
                'option_d' => 'Toad',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Em que ano foi lançado o primeiro jogo da série The Legend of Zelda?',
                'option_a' => '1985',
                'option_b' => '1986',
                'option_c' => '1987',
                'option_d' => '1988',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual empresa criou o Sonic the Hedgehog?',
                'option_a' => 'Nintendo',
                'option_b' => 'Sega',
                'option_c' => 'Capcom',
                'option_d' => 'Konami',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual é o nome da princesa que Bowser sempre sequestra na série Mario?',
                'option_a' => 'Zelda',
                'option_b' => 'Daisy',
                'option_c' => 'Peach',
                'option_d' => 'Rosalina',
                'correct_answer' => 'c',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual é o jogo de videogame mais vendido de todos os tempos?',
                'option_a' => 'Tetris',
                'option_b' => 'Minecraft',
                'option_c' => 'GTA V',
                'option_d' => 'Wii Sports',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Em qual jogo você controla um personagem chamado Master Chief?',
                'option_a' => 'Halo',
                'option_b' => 'Call of Duty',
                'option_c' => 'Destiny',
                'option_d' => 'Gears of War',
                'correct_answer' => 'a',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual é o nome do protagonista da série The Witcher?',
                'option_a' => 'Geralt',
                'option_b' => 'Vesemir',
                'option_c' => 'Lambert',
                'option_d' => 'Eskel',
                'correct_answer' => 'a',
                'category' => 'videogames',
            ],
            [
                'question' => 'Em qual jogo você pode encontrar criaturas chamadas Pokémon?',
                'option_a' => 'Digimon',
                'option_b' => 'Monster Hunter',
                'option_c' => 'Pokémon',
                'option_d' => 'Tem-Tem',
                'correct_answer' => 'c',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual console da Nintendo popularizou os controles de movimento?',
                'option_a' => 'GameCube',
                'option_b' => 'Wii',
                'option_c' => 'Switch',
                'option_d' => 'Nintendo 64',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual é o nome do cachorro companheiro em Duck Hunt?',
                'option_a' => 'Rex',
                'option_b' => 'Buddy',
                'option_c' => 'Dog',
                'option_d' => 'Max',
                'correct_answer' => 'c',
                'category' => 'videogames',
            ],
            [
                'question' => 'Em qual jogo você defende sua casa de zumbis usando plantas?',
                'option_a' => 'Zombies Ate My Neighbors',
                'option_b' => 'Plants vs Zombies',
                'option_c' => 'Dead Rising',
                'option_d' => 'Left 4 Dead',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual empresa desenvolveu o jogo Fortnite?',
                'option_a' => 'Activision',
                'option_b' => 'Epic Games',
                'option_c' => 'EA',
                'option_d' => 'Ubisoft',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Em que jogo você controla um personagem chamado Gordon Freeman?',
                'option_a' => 'Portal',
                'option_b' => 'Half-Life',
                'option_c' => 'Doom',
                'option_d' => 'Bioshock',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual é o nome da espada icônica de Link em The Legend of Zelda?',
                'option_a' => 'Master Sword',
                'option_b' => 'Excalibur',
                'option_c' => 'Buster Sword',
                'option_d' => 'Hylian Sword',
                'correct_answer' => 'a',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual jogo apresenta a cidade de Raccoon City?',
                'option_a' => 'Silent Hill',
                'option_b' => 'Resident Evil',
                'option_c' => 'Dead Space',
                'option_d' => 'The Last of Us',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Em qual jogo você pode construir e sobreviver em um mundo de blocos?',
                'option_a' => 'Roblox',
                'option_b' => 'Terraria',
                'option_c' => 'Minecraft',
                'option_d' => 'Lego Worlds',
                'correct_answer' => 'c',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual personagem é conhecido por dizer "It\'s-a me!"?',
                'option_a' => 'Luigi',
                'option_b' => 'Wario',
                'option_c' => 'Mario',
                'option_d' => 'Waluigi',
                'correct_answer' => 'c',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual é o nome do protagonista de God of War?',
                'option_a' => 'Zeus',
                'option_b' => 'Ares',
                'option_c' => 'Kratos',
                'option_d' => 'Hades',
                'correct_answer' => 'c',
                'category' => 'videogames',
            ],
            [
                'question' => 'Em qual jogo você coleta anéis dourados?',
                'option_a' => 'Super Mario',
                'option_b' => 'Sonic',
                'option_c' => 'Crash Bandicoot',
                'option_d' => 'Spyro',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual empresa criou o PlayStation?',
                'option_a' => 'Microsoft',
                'option_b' => 'Sony',
                'option_c' => 'Sega',
                'option_d' => 'Nintendo',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Em qual jogo você controla um personagem chamado Lara Croft?',
                'option_a' => 'Uncharted',
                'option_b' => 'Assassin\'s Creed',
                'option_c' => 'Tomb Raider',
                'option_d' => 'Prince of Persia',
                'correct_answer' => 'c',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual é o mascote da Capcom conhecido por lutar em torneios?',
                'option_a' => 'Ryu',
                'option_b' => 'Mega Man',
                'option_c' => 'Arthur',
                'option_d' => 'Dante',
                'correct_answer' => 'a',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual jogo Battle Royale foi desenvolvido pela PUBG Corporation?',
                'option_a' => 'Fortnite',
                'option_b' => 'Apex Legends',
                'option_c' => 'PUBG',
                'option_d' => 'Call of Duty Warzone',
                'correct_answer' => 'c',
                'category' => 'videogames',
            ],
            [
                'question' => 'Em qual jogo você explora o mundo pós-apocalíptico de Boston?',
                'option_a' => 'Fallout 4',
                'option_b' => 'The Last of Us',
                'option_c' => 'Metro Exodus',
                'option_d' => 'Days Gone',
                'correct_answer' => 'a',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual é o nome do personagem principal de Assassin\'s Creed II?',
                'option_a' => 'Altair',
                'option_b' => 'Ezio',
                'option_c' => 'Connor',
                'option_d' => 'Edward',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual jogo apresenta os personagens Trevor, Michael e Franklin?',
                'option_a' => 'Red Dead Redemption',
                'option_b' => 'GTA IV',
                'option_c' => 'GTA V',
                'option_d' => 'Saints Row',
                'correct_answer' => 'c',
                'category' => 'videogames',
            ],
            [
                'question' => 'Em qual jogo você joga como um caçador de monstros?',
                'option_a' => 'Dark Souls',
                'option_b' => 'Bloodborne',
                'option_c' => 'Monster Hunter',
                'option_d' => 'The Witcher',
                'correct_answer' => 'c',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual é o nome do fantasma que ajuda Pac-Man?',
                'option_a' => 'Não existe',
                'option_b' => 'Blinky',
                'option_c' => 'Pinky',
                'option_d' => 'Inky',
                'correct_answer' => 'a',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual jogo de corrida apresenta personagens da Nintendo?',
                'option_a' => 'Gran Turismo',
                'option_b' => 'Need for Speed',
                'option_c' => 'Mario Kart',
                'option_d' => 'Forza',
                'correct_answer' => 'c',
                'category' => 'videogames',
            ],
            [
                'question' => 'Em qual jogo você controla um personagem chamado Joel?',
                'option_a' => 'Uncharted',
                'option_b' => 'The Last of Us',
                'option_c' => 'Days Gone',
                'option_d' => 'God of War',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual é o nome do irmão mais novo de Mario?',
                'option_a' => 'Wario',
                'option_b' => 'Waluigi',
                'option_c' => 'Luigi',
                'option_d' => 'Yoshi',
                'correct_answer' => 'c',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual jogo de luta apresenta personagens como Scorpion e Sub-Zero?',
                'option_a' => 'Street Fighter',
                'option_b' => 'Tekken',
                'option_c' => 'Mortal Kombat',
                'option_d' => 'Soul Calibur',
                'correct_answer' => 'c',
                'category' => 'videogames',
            ],
            [
                'question' => 'Em qual jogo você pode escolher entre Charmander, Squirtle e Bulbasaur?',
                'option_a' => 'Pokémon Red/Blue',
                'option_b' => 'Pokémon Gold/Silver',
                'option_c' => 'Pokémon Ruby/Sapphire',
                'option_d' => 'Pokémon Black/White',
                'correct_answer' => 'a',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual empresa desenvolveu o jogo Overwatch?',
                'option_a' => 'Riot Games',
                'option_b' => 'Blizzard',
                'option_c' => 'Valve',
                'option_d' => 'Epic Games',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual é o nome da nave espacial em Metroid?',
                'option_a' => 'Arwing',
                'option_b' => 'Gunship',
                'option_c' => 'Vic Viper',
                'option_d' => 'Starfox',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Em qual jogo você constrói portais azuis e laranjas?',
                'option_a' => 'Half-Life',
                'option_b' => 'Portal',
                'option_c' => 'The Talos Principle',
                'option_d' => 'Q.U.B.E.',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual é o nome do dragão roxo protagonista de uma série de jogos da PlayStation?',
                'option_a' => 'Cynder',
                'option_b' => 'Spyro',
                'option_c' => 'Draco',
                'option_d' => 'Mushu',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual jogo apresenta o personagem Nathan Drake?',
                'option_a' => 'Tomb Raider',
                'option_b' => 'Uncharted',
                'option_c' => 'Assassin\'s Creed',
                'option_d' => 'Far Cry',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Em qual jogo você pode ser um Dragonborn?',
                'option_a' => 'Dragon Age',
                'option_b' => 'Dark Souls',
                'option_c' => 'The Elder Scrolls V: Skyrim',
                'option_d' => 'The Witcher',
                'correct_answer' => 'c',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual é o nome do personagem principal de Metal Gear Solid?',
                'option_a' => 'Big Boss',
                'option_b' => 'Solid Snake',
                'option_c' => 'Liquid Snake',
                'option_d' => 'Raiden',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual jogo de corrida arcade é conhecido por dizer "Sega!" no início?',
                'option_a' => 'Daytona USA',
                'option_b' => 'Out Run',
                'option_c' => 'Crazy Taxi',
                'option_d' => 'Virtua Racing',
                'correct_answer' => 'a',
                'category' => 'videogames',
            ],
            [
                'question' => 'Em qual jogo você controla um personagem chamado Samus Aran?',
                'option_a' => 'Mega Man',
                'option_b' => 'Metroid',
                'option_c' => 'Halo',
                'option_d' => 'Doom',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual é o nome do principal antagonista da série Sonic?',
                'option_a' => 'Dr. Robotnik/Eggman',
                'option_b' => 'Metal Sonic',
                'option_c' => 'Shadow',
                'option_d' => 'Knuckles',
                'correct_answer' => 'a',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual jogo apresenta um personagem que usa uma pistola portal e um cubo companion?',
                'option_a' => 'Half-Life',
                'option_b' => 'Portal',
                'option_c' => 'Quantum Break',
                'option_d' => 'Control',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Em qual jogo você joga como um bandicoot?',
                'option_a' => 'Spyro',
                'option_b' => 'Ratchet & Clank',
                'option_c' => 'Crash Bandicoot',
                'option_d' => 'Jak and Daxter',
                'correct_answer' => 'c',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual é o nome da IA em Portal?',
                'option_a' => 'HAL',
                'option_b' => 'JARVIS',
                'option_c' => 'GLaDOS',
                'option_d' => 'Cortana',
                'correct_answer' => 'c',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual jogo permite que você capture criaturas em Pokébolas?',
                'option_a' => 'Digimon',
                'option_b' => 'Monster Rancher',
                'option_c' => 'Pokémon',
                'option_d' => 'Yo-Kai Watch',
                'correct_answer' => 'c',
                'category' => 'videogames',
            ],
            [
                'question' => 'Em qual jogo você é um caçador de recompensas espacial chamado Samus?',
                'option_a' => 'Star Fox',
                'option_b' => 'Metroid',
                'option_c' => 'Mass Effect',
                'option_d' => 'Dead Space',
                'correct_answer' => 'b',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual é o nome do vilão principal em The Legend of Zelda?',
                'option_a' => 'Ganon/Ganondorf',
                'option_b' => 'Vaati',
                'option_c' => 'Zant',
                'option_d' => 'Ghirahim',
                'correct_answer' => 'a',
                'category' => 'videogames',
            ],
            [
                'question' => 'Qual jogo de estratégia em tempo real apresenta as raças Terran, Protoss e Zerg?',
                'option_a' => 'Warcraft',
                'option_b' => 'Age of Empires',
                'option_c' => 'StarCraft',
                'option_d' => 'Command & Conquer',
                'correct_answer' => 'c',
                'category' => 'videogames',
            ],
        ];

        foreach ($questions as $question) {
            Question::create($question);
        }
    }
}
