<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Question;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $questions = [
            [
                'question' => 'Quanto é 7 + 5?',
                'option_a' => '10',
                'option_b' => '11',
                'option_c' => '12',
                'option_d' => '13',
                'option_e' => '14',
                'correct_answer' => 'c',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Quanto é 9 - 4?',
                'option_a' => '3',
                'option_b' => '4',
                'option_c' => '5',
                'option_d' => '6',
                'option_e' => '7',
                'correct_answer' => 'c',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Quanto é 6 × 8?',
                'option_a' => '42',
                'option_b' => '46',
                'option_c' => '48',
                'option_d' => '54',
                'option_e' => '56',
                'correct_answer' => 'c',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Quanto é 81 ÷ 9?',
                'option_a' => '7',
                'option_b' => '8',
                'option_c' => '9',
                'option_d' => '10',
                'option_e' => '11',
                'correct_answer' => 'c',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Qual é a metade de 50?',
                'option_a' => '20',
                'option_b' => '25',
                'option_c' => '30',
                'option_d' => '35',
                'option_e' => '40',
                'correct_answer' => 'b',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Quanto é 2^5 (2 elevado a 5)?',
                'option_a' => '16',
                'option_b' => '24',
                'option_c' => '32',
                'option_d' => '64',
                'option_e' => '128',
                'correct_answer' => 'c',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Qual o valor de π (aproximado) até duas casas decimais?',
                'option_a' => '3,00',
                'option_b' => '3,14',
                'option_c' => '3,41',
                'option_d' => '3,41',
                'option_e' => '3,50',
                'correct_answer' => 'b',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Quanto é 15% de 200?',
                'option_a' => '20',
                'option_b' => '25',
                'option_c' => '30',
                'option_d' => '35',
                'option_e' => '40',
                'correct_answer' => 'c',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Qual é o mínimo múltiplo comum (MMC) de 4 e 6?',
                'option_a' => '10',
                'option_b' => '12',
                'option_c' => '14',
                'option_d' => '16',
                'option_e' => '18',
                'correct_answer' => 'b',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Quanto é 100 - 37?',
                'option_a' => '63',
                'option_b' => '64',
                'option_c' => '65',
                'option_d' => '66',
                'option_e' => '67',
                'correct_answer' => 'a',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Qual é a soma de 1 + 2 + 3 + 4 + 5?',
                'option_a' => '10',
                'option_b' => '11',
                'option_c' => '12',
                'option_d' => '13',
                'option_e' => '15',
                'correct_answer' => 'e',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Se um número x satisfaça x + 3 = 10, qual é x?',
                'option_a' => '6',
                'option_b' => '7',
                'option_c' => '8',
                'option_d' => '9',
                'option_e' => '10',
                'correct_answer' => 'b',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Quanto é a média aritmética de 4, 6 e 10?',
                'option_a' => '6',
                'option_b' => '7',
                'option_c' => '8',
                'option_d' => '9',
                'option_e' => '10',
                'correct_answer' => 'b',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Qual é o valor de 0,25 em forma de fração?',
                'option_a' => '1/2',
                'option_b' => '1/3',
                'option_c' => '1/4',
                'option_d' => '1/5',
                'option_e' => '1/6',
                'correct_answer' => 'c',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Quanto é 11 × 11?',
                'option_a' => '111',
                'option_b' => '121',
                'option_c' => '131',
                'option_d' => '141',
                'option_e' => '151',
                'correct_answer' => 'b',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Qual número completa a sequência: 2, 4, 6, __?',
                'option_a' => '7',
                'option_b' => '8',
                'option_c' => '9',
                'option_d' => '10',
                'option_e' => '12',
                'correct_answer' => 'b',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Quanto é 5! (5 fatorial)?',
                'option_a' => '60',
                'option_b' => '90',
                'option_c' => '100',
                'option_d' => '120',
                'option_e' => '150',
                'correct_answer' => 'd',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Qual é a área de um quadrado de lado 7?',
                'option_a' => '14',
                'option_b' => '28',
                'option_c' => '49',
                'option_d' => '56',
                'option_e' => '64',
                'correct_answer' => 'c',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Se um trem parte às 14:00 e viaja 3 horas, que horas são quando chega?',
                'option_a' => '16:00',
                'option_b' => '17:00',
                'option_c' => '17:30',
                'option_d' => '18:00',
                'option_e' => '20:00',
                'correct_answer' => 'b',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Quanto é 14 + 28?',
                'option_a' => '32',
                'option_b' => '36',
                'option_c' => '40',
                'option_d' => '42',
                'option_e' => '44',
                'correct_answer' => 'd',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Quanto é 20% de 150?',
                'option_a' => '20',
                'option_b' => '25',
                'option_c' => '30',
                'option_d' => '35',
                'option_e' => '40',
                'correct_answer' => 'c',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Qual é a raiz quadrada de 144?',
                'option_a' => '10',
                'option_b' => '11',
                'option_c' => '12',
                'option_d' => '13',
                'option_e' => '14',
                'correct_answer' => 'c',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Quanto é 7 × 7?',
                'option_a' => '42',
                'option_b' => '46',
                'option_c' => '49',
                'option_d' => '56',
                'option_e' => '63',
                'correct_answer' => 'c',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Quanto é 100 ÷ 4?',
                'option_a' => '20',
                'option_b' => '24',
                'option_c' => '25',
                'option_d' => '26',
                'option_e' => '30',
                'correct_answer' => 'c',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Qual é o dobro de 37?',
                'option_a' => '64',
                'option_b' => '70',
                'option_c' => '72',
                'option_d' => '74',
                'option_e' => '76',
                'correct_answer' => 'd',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Quanto é 3/4 de 100?',
                'option_a' => '50',
                'option_b' => '60',
                'option_c' => '70',
                'option_d' => '75',
                'option_e' => '80',
                'correct_answer' => 'd',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Qual é o perímetro de um quadrado de lado 9?',
                'option_a' => '27',
                'option_b' => '36',
                'option_c' => '45',
                'option_d' => '54',
                'option_e' => '81',
                'correct_answer' => 'b',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Quanto é 18 - 9 + 3?',
                'option_a' => '8',
                'option_b' => '10',
                'option_c' => '12',
                'option_d' => '14',
                'option_e' => '16',
                'correct_answer' => 'b',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Quanto é 2 + 3 × 4? (use ordem das operações)',
                'option_a' => '20',
                'option_b' => '14',
                'option_c' => '18',
                'option_d' => '10',
                'option_e' => '16',
                'correct_answer' => 'b',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Qual é a forma decimal de 3/5?',
                'option_a' => '0,3',
                'option_b' => '0,4',
                'option_c' => '0,5',
                'option_d' => '0,6',
                'option_e' => '0,7',
                'correct_answer' => 'd',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Se você dividir 45 por 5, qual o resultado?',
                'option_a' => '7',
                'option_b' => '8',
                'option_c' => '9',
                'option_d' => '10',
                'option_e' => '11',
                'correct_answer' => 'c',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Qual é o antecessor de 1000?',
                'option_a' => '998',
                'option_b' => '999',
                'option_c' => '1000',
                'option_d' => '1001',
                'option_e' => '1002',
                'correct_answer' => 'b',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Quanto é 4^3 (4 ao cubo)?',
                'option_a' => '16',
                'option_b' => '32',
                'option_c' => '64',
                'option_d' => '48',
                'option_e' => '80',
                'correct_answer' => 'c',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Qual é a diferença entre 1000 e 457?',
                'option_a' => '543',
                'option_b' => '553',
                'option_c' => '563',
                'option_d' => '573',
                'option_e' => '583',
                'correct_answer' => 'a',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Se você multiplicar 0 por qualquer número, o resultado é?',
                'option_a' => '0',
                'option_b' => '1',
                'option_c' => 'o próprio número',
                'option_d' => 'infinito',
                'option_e' => 'indeterminado',
                'correct_answer' => 'a',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Qual é o próximo número depois de 29?',
                'option_a' => '28',
                'option_b' => '29',
                'option_c' => '30',
                'option_d' => '31',
                'option_e' => '32',
                'correct_answer' => 'c',
                'category' => 'matematica_basica',
            ],
            [
                'question' => 'Quantos minutos há em 2 horas?',
                'option_a' => '60',
                'option_b' => '90',
                'option_c' => '100',
                'option_d' => '120',
                'option_e' => '180',
                'correct_answer' => 'd',
                'category' => 'matematica_basica',
            ],
        ];

        foreach ($questions as $question) {
            // ensure correct structure for DB columns (option_e may be nullable on older setups)
            Question::create($question);
        }
    }
}
